name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-pre-commit:
    name: Pre-Commit with Latest Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Min/Max Versions
        id: min-max
        uses: clowdhaus/terraform-min-max@v1.1.1

      - name: Pre-commit Terraform ${{ steps['min-max'].outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.6.0
        with:
          terraform-version: ${{ steps['min-max'].outputs.maxVersion }}
